Repository tempesta-tech/tempesta, pull requests merged in 2018-03, with the labels that each got.

#913 Fix #844: Avoid frang and sticky processing for whitelist requests.
  etc/tempesta_fw.conf
  tempesta_fw/classifier/frang.c
  tempesta_fw/http.c
  tempesta_fw/http.h
  tempesta_fw/http_sess.c
  tempesta_fw/ss_skb.c
Labels: ready for review

#928 Fix leaks test
  tempesta_fw/t/functional/leaks/test_leak.py
Labels: ready for review

#916 Fix #76 #886 #908 #911, many other fixes and optimizations
  linux-4.9.35.patch
  tempesta_fw/apm.c
  tempesta_fw/cfg.c
  tempesta_fw/client.h
  tempesta_fw/http.c
  tempesta_fw/main.c
  tempesta_fw/peer.h
  tempesta_fw/procfs.c
  tempesta_fw/sched/tfw_sched_hash.c
  tempesta_fw/sched/tfw_sched_http.c
  tempesta_fw/sched/tfw_sched_ratio.c
  tempesta_fw/server.c
  tempesta_fw/server.h
  tempesta_fw/sock.c
  tempesta_fw/sock_clnt.c
  tempesta_fw/sock_srv.c
  tempesta_fw/t/unit/kallsyms_helper.c
  tempesta_fw/t/unit/sched_helper.c
  tempesta_fw/t/unit/test_http_sticky.c
  tempesta_fw/tempesta_fw.h
Labels: ready for review

#877 Fix #672: Add health monitoring for backend servers.
  etc/tempesta_fw.conf
  tempesta_fw/apm.c
  tempesta_fw/apm.h
  tempesta_fw/cfg.c
  tempesta_fw/cfg.h
  tempesta_fw/classifier/frang.c
  tempesta_fw/http.c
  tempesta_fw/http.h
  tempesta_fw/http_msg.c
  tempesta_fw/http_msg.h
  tempesta_fw/http_sess.c
  tempesta_fw/procfs.c
  tempesta_fw/sched/tfw_sched_hash.c
  tempesta_fw/sched/tfw_sched_ratio.c
  tempesta_fw/server.h
  tempesta_fw/sock_srv.c
  tempesta_fw/str.c
  tempesta_fw/str.h
  tempesta_fw/t/functional/health_monitoring/__init__.py
  tempesta_fw/t/functional/health_monitoring/test_health_monitor.py
  tempesta_fw/t/functional/helpers/chains.py
  tempesta_fw/t/functional/helpers/control.py
  tempesta_fw/t/functional/helpers/tempesta.py
  tempesta_fw/t/functional/reconf/__init__.py
  tempesta_fw/t/functional/reconf/test_stress_health_monitor.py
  tempesta_fw/t/functional/testers/functional.py
  tempesta_fw/t/unit/test_sched_hash.c
  tempesta_fw/t/unit/test_sched_ratio.c
  tempesta_fw/t/unit/test_tfw_str.c
Labels: ready for review

#935 Fix #925; improve WQ testing for #922
  tempesta_db/core/file.c
  tempesta_db/core/htrie.c
  tempesta_fw/filter.c
  tempesta_fw/sock_clnt.c
  tempesta_fw/t/unit/test_wq.c
Labels: ready for review

#942 Fix restarting without unloading modules
  tempesta_fw/apm.c
  tempesta_fw/cache.c
  tempesta_fw/classifier.c
  tempesta_fw/classifier.h
  tempesta_fw/classifier/frang.c
  tempesta_fw/filter.c
  tempesta_fw/http.c
  tempesta_fw/http_parser.c
  tempesta_fw/http_sess.c
  tempesta_fw/sock_clnt.c
  tempesta_fw/str.h
  tempesta_fw/t/unit/test_http_sticky.c
  tempesta_fw/tls.c
Labels: ready for review

#937 Fix #922.
  tempesta_fw/work_queue.c
Labels: ready for review

#939 [Tests] Fix server connections failovering functional tests
  tempesta_fw/t/functional/helpers/deproxy.py
  tempesta_fw/t/functional/regression/test_srv_failovering.py
Labels: ready for review

#944 Fix #936: firstly print warning and only after that free the request
  tempesta_fw/http.c
Labels: ready for review

#946 Fix tf_cfg.ConfigError()
  tempesta_fw/t/functional/helpers/tf_cfg.py
Labels: ready for review

#884 Early bind of response and request
  tempesta_fw/cache.c
  tempesta_fw/cache.h
  tempesta_fw/classifier/frang.c
  tempesta_fw/http.c
  tempesta_fw/http.h
  tempesta_fw/http_msg.c
  tempesta_fw/http_msg.h
  tempesta_fw/http_parser.c
  tempesta_fw/http_sess.c
  tempesta_fw/http_sess.h
  tempesta_fw/sched/tfw_sched_hash.c
  tempesta_fw/sched/tfw_sched_ratio.c
  tempesta_fw/t/functional/helpers/__init__.py
  tempesta_fw/t/functional/helpers/deproxy.py
  tempesta_fw/t/functional/helpers/dmesg.py
  tempesta_fw/t/functional/helpers/remote.py
  tempesta_fw/t/functional/msg_sequence/__init__.py
  tempesta_fw/t/functional/msg_sequence/test_pairing.py
  tempesta_fw/t/functional/run_tests.py
  tempesta_fw/t/functional/testers/functional.py
  tempesta_fw/t/unit/helpers.c
  tempesta_fw/t/unit/test_http_parser.c
  tempesta_fw/t/unit/test_http_sticky.c
Labels: ready for review

#885 1M backends
  tempesta_fw/t/functional/helpers/deproxy.py
  tempesta_fw/t/functional/helpers/tempesta.py
  tempesta_fw/t/functional/helpers/tf_cfg.py
  tempesta_fw/t/functional/testers/stress.py
  tempesta_fw/t/functional/tests_config.ini.sample
  tempesta_fw/t/functional/very_many_backends/__init__.py
  tempesta_fw/t/functional/very_many_backends/multi_backend.py
  tempesta_fw/t/functional/very_many_backends/test_deadtime_1M.py
  tempesta_fw/t/functional/very_many_backends/test_stress_1M.py
Labels: ready for review

#955 Fix #926
  linux-4.9.35.patch
Labels: ready for review

#897 Long body in responses and requests
  tempesta_fw/t/functional/health_monitoring/test_health_monitor.py
  tempesta_fw/t/functional/helpers/__init__.py
  tempesta_fw/t/functional/helpers/chains.py
  tempesta_fw/t/functional/helpers/control.py
  tempesta_fw/t/functional/helpers/deproxy.py
  tempesta_fw/t/functional/helpers/wrk.py
  tempesta_fw/t/functional/long_body/__init__.py
  tempesta_fw/t/functional/long_body/body_generator.py
  tempesta_fw/t/functional/long_body/test_long_request.py
  tempesta_fw/t/functional/long_body/test_long_response.py
  tempesta_fw/t/functional/long_body/test_request_wrong_length.py
  tempesta_fw/t/functional/long_body/test_response_wrong_length.py
  tempesta_fw/t/functional/long_body/tester.py
  tempesta_fw/t/functional/msg_sequence/test_pairing.py
  tempesta_fw/t/functional/regression/test_invalid.py
  tempesta_fw/t/functional/regression/test_shutdown.py
  tempesta_fw/t/functional/sched/test_http.py
  tempesta_fw/t/functional/testers/functional.py
Labels: ready for review

#948 Fix 945 - mixed_tests
  tempesta_fw/t/functional/helpers/control.py
  tempesta_fw/t/functional/helpers/nginx.py
  tempesta_fw/t/functional/leaks/test_leak.py
  tempesta_fw/t/functional/long_body/test_long_response.py
  tempesta_fw/t/functional/mixed_requests/mixed_test.py
  tempesta_fw/t/functional/mixed_requests/test_mixed.py
  tempesta_fw/t/functional/regression/test_reboot.py
  tempesta_fw/t/functional/regression/test_stress_pipeline.py
  tempesta_fw/t/functional/testers/stress.py
  tempesta_fw/t/functional/tls/test_tls_stress.py
  tempesta_fw/t/functional/wrk/connect.lua
  tempesta_fw/t/functional/wrk/cookie-many-clients.lua
  tempesta_fw/t/functional/wrk/cookie-one-client.lua
  tempesta_fw/t/functional/wrk/get_post.lua
  tempesta_fw/t/functional/wrk/get_real_pipelined.lua
  tempesta_fw/t/functional/wrk/head_get.lua
  tempesta_fw/t/functional/wrk/mixed.lua
  tempesta_fw/t/functional/wrk/pipeline.lua
  tempesta_fw/t/functional/wrk/post_empty.lua
  tempesta_fw/t/functional/wrk/post_small.lua
  tempesta_fw/t/functional/wrk/results.lua
  tempesta_fw/t/functional/wrk/trace.lua
Labels: ready for review

#961 func tests: Fix 'too many values to unpack' error
  tempesta_fw/t/functional/reconf/reconf_stress.py
Labels: crucial

#952 Fix #903: add logging for all error responses.
  tempesta_fw/cache.c
  tempesta_fw/http.c
  tempesta_fw/http.h
  tempesta_fw/t/functional/helpers/chains.py
  tempesta_fw/t/unit/test_http_sticky.c
Labels: ready for review

#969 Fix releasing of requests and responses on client disconnects
  tempesta_fw/http.c
  tempesta_fw/http_msg.c
  tempesta_fw/server.c
Labels: crucial, ready for review

#970 Resolve issues from static analyzer report.
  tempesta_fw/cache.c
  tempesta_fw/sched/tfw_sched_ratio.c
  tempesta_fw/t/unit/test_http_parser.c
Labels: ready for review

#972 Fix #971
  tempesta_fw/http.c
  tempesta_fw/http_msg.c
Labels: crucial, ready for review

#968 Test control
  tempesta_fw/t/functional/run_tests.py
Labels: ready for review

#979 Fix #978: mark started flag as false after failed start on reload.
  tempesta_fw/main.c
  tempesta_fw/server.c
Labels: ready for review

#982 Return 1 for failed unit tests
  tempesta_fw/t/unit/run_all_tests.sh
Labels: ready for review

#983 Fix #918: release connection if its' reference count is zero.
  tempesta_fw/connection.h
  tempesta_fw/sock_srv.c
  tempesta_fw/tempesta_fw.h
Labels: ready for review

#992 Backport fix for #918.
  tempesta_fw/connection.h
  tempesta_fw/sock_srv.c
  tempesta_fw/tempesta_fw.h
Labels: ready for review
