Repository tempesta-tech/tempesta, pull requests merged in 2019-03, with the labels that each got.

#1205 Add forgotten http_ctext_vchar_brange config option.
  tempesta_fw/http.c
  tempesta_fw/str_simd.c
Labels: crucial, ready for review

#1206 fix encoding to chunked: chunk size is hex digit, not decimal
  tempesta_fw/http_msg.c
  tempesta_fw/str.c
  tempesta_fw/str.h
  tempesta_fw/t/unit/test_tfw_str.c
Labels: ready for review

#1201 Fix #1131: use GCC jumps to labels stored as pointers.
  Makefile
  README.md
  lib/fsm.h
  tempesta_fw/Makefile
  tempesta_fw/cfg.c
  tempesta_fw/connection.h
  tempesta_fw/http.h
  tempesta_fw/http_limits.c
  tempesta_fw/http_norm.h
  tempesta_fw/http_parser.c
  tempesta_fw/http_parser.h
  tempesta_fw/t/unit/test_http_parser.c
  tempesta_fw/t/unit/test_http_sticky.c
  tempesta_fw/tempesta_fw.h
  tls/tls_internal.h
  tls/ttls.h
Labels: ready for review

#1219 #1181: GCOV compilation option
  Makefile
  lib/Makefile
  scripts/gcov_gather.sh
  tempesta_db/core/Makefile
  tempesta_fw/Makefile
  tls/Makefile
Labels: ready for review

#1209 fix #1189: correctly fill header part of skb when writing data into p…
  tempesta_fw/cache.c
  tempesta_fw/http_msg.c
  tempesta_fw/msg.c
  tempesta_fw/msg.h
  tempesta_fw/ss_skb.h
Labels: ready for review

#1223 readme: add packaging readme
  pkg/README.md
Labels: doc

#1225 Fix #1222
  tempesta_fw/http_parser.c
  tempesta_fw/t/unit/test_http_parser.c
Labels: ready for review
