Repository tempesta-tech/tempesta, pull requests merged in 2021-01, with the labels that each got.

#1481 Performance optimizations for NIST p256 curve
  Makefile
  tempesta_fw/http_limits.c
  tls/bignum.c
  tls/bignum_asm.h
  tls/bignum_x86-64.S
  tls/ciphersuites.c
  tls/ec_25519.c
  tls/ec_p256.c
  tls/ec_p384.c
  tls/ecp.c
  tls/ecp.h
  tls/mpool.h
  tls/oid.c
  tls/oid.h
  tls/pk.c
  tls/t/benchmark.c
  tls/t/run_tests.sh
  tls/t/test_ec_25519.c
  tls/t/test_ec_p256.c
  tls/t/test_ec_p384.c
  tls/t/test_ecdh_p256.c
  tls/t/test_ecdsa_p256.c
  tls/t/test_mpi.c
  tls/t/test_mpi_math.c
  tls/t/test_rsa.c
  tls/t/tgen_ec256.c
  tls/t/ttls_mocks.h
  tls/tls_srv.c
  tls/ttls.h
  tls/x509_crt.c
Labels: TLS, performance

#1484 Fix invalid error messages if js_challenge points to invalid file
  scripts/tempesta.sh
  scripts/update_template.pl
  tempesta_fw/http_sess_conf.c
Labels: ready for review

#1486 Fix frang on h2 requests
  tempesta_fw/http.c
  tempesta_fw/http.h
  tempesta_fw/http_limits.c
  tempesta_fw/http_msg.c
  tempesta_fw/http_parser.c
Labels: h2, ready for review
